USE [master]
GO

/****** Object:  Database [ChampionDB]    Script Date: 18/12/2019 15:10:49 ******/
CREATE DATABASE [ChampionDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ChammpionDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ChammpionDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ChammpionDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ChammpionDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ChampionDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ChampionDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ChampionDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ChampionDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ChampionDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ChampionDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ChampionDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ChampionDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ChampionDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ChampionDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ChampionDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ChampionDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ChampionDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ChampionDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ChampionDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ChampionDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ChampionDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ChampionDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ChampionDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ChampionDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ChampionDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ChampionDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ChampionDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ChampionDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ChampionDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ChampionDB] SET  MULTI_USER 
GO

ALTER DATABASE [ChampionDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ChampionDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ChampionDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ChampionDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ChampionDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ChampionDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ChampionDB] SET  READ_WRITE 
GO


